addr: localhost
admin_bearer_token: a9209fd5-0628-40ac-8ff5-d9f46f90846a
app_name: Overlay API v0.0.0
mongo:
    database: overlay
    uri: mongodb://localhost:27017
port: 3000
server_header: Overlay API
