version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: overlay-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
