version: '3'

vars:
  OPENAPI_FILE: api/openapi/server/api.yaml
  SWAGGER_FILE: docs/api/openapi/overlay-services.yaml

tasks:
  default:
    cmds:
      - task --list
    desc: Display all available tasks.

  execute-unit-tests:
    desc: Execute all unit test suites to verify functionality.
    cmds:
      - go test ./... -failfast -count=1
    silent: true

  oapi-codegen:
    desc: Generate HTTP server, response & request models based on OpenAPI spec.
    cmds:
      - go generate ./...
    silent: true

  swagger-cli-install:
    desc: Install swagger-cli globally using npm.
    cmds:
      - npm install -g swagger-cli
    silent: true

  swagger-doc-gen:
    desc: Bundle OpenAPI spec.
    cmds:
      - task oapi-codegen
      - swagger-cli bundle {{.OPENAPI_FILE}} -o {{.SWAGGER_FILE}} -t yaml
    silent: true

  swagger-ui-up:
    desc: Bundle OpenAPI spec and start Swagger UI with Docker Compose.
    cmds:
      - task swagger-doc-gen
      - swagger-cli validate {{.OPENAPI_FILE}}
      - docker-compose up -d
    silent: true

  swagger-ui-down:
    desc: Bundle OpenAPI spec and stop Swagger UI containers.
    cmds:
      - task swagger-doc-gen
      - docker-compose down
    silent: true

  swagger-cleanup:
    desc: Remove generated Swagger files and stop running containers if needed.
    cmds:
      - docker-compose down || true
      - rm -f {{.SWAGGER_FILE}}
    silent: true
