// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// LookupQuestionBody defines model for LookupQuestionBody.
type LookupQuestionBody struct {
	// Query The query data as JSON
	Query *map[string]interface{} `json:"query,omitempty"`

	// Service The name of the service
	Service string `json:"service"`
}
