// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// RequestForeignGASPNodeBody defines model for RequestForeignGASPNodeBody.
type RequestForeignGASPNodeBody struct {
	// GraphID The graph ID in the format of "txID.outputIndex"
	GraphID string `json:"graphID"`

	// OutputIndex The output index
	OutputIndex uint32 `json:"outputIndex"`

	// TxID The transaction ID
	TxID string `json:"txID"`
}
