// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// GetTopicManagerDocumentationParams defines parameters for GetTopicManagerDocumentation.
type GetTopicManagerDocumentationParams struct {
	// TopicManager The name of the topic manager to retrieve documentation for
	TopicManager string `form:"topicManager" json:"topicManager"`
}

// SubmitTransactionParams defines parameters for SubmitTransaction.
type SubmitTransactionParams struct {
	XTopics []string `json:"x-topics"`
}
