// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// ArcIngestBody defines model for ArcIngestBody.
type ArcIngestBody struct {
	// BlockHeight Block height where the transaction was mined
	BlockHeight uint32 `json:"blockHeight"`

	// MerklePath Merkle path in hexadecimal format
	MerklePath string `json:"merklePath"`

	// Txid Transaction ID in hexadecimal format
	Txid string `json:"txid"`
}
