// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdmittanceInstructions defines model for AdmittanceInstructions.
type AdmittanceInstructions struct {
	AncillaryTxIDs []string `json:"AncillaryTxIDs"`
	CoinsRemoved   []uint32 `json:"CoinsRemoved"`
	CoinsToRetain  []uint32 `json:"CoinsToRetain"`
	OutputsToAdmit []uint32 `json:"OutputsToAdmit"`
}

// GASPInitialResponse defines model for GASPInitialResponse.
type GASPInitialResponse struct {
	// Since Timestamp for incremental sync
	Since uint64 `json:"since"`

	// UtxoList List of UTXOs
	UtxoList []Outpoint `json:"utxoList"`
}

// GASPNode GASP node data structure
type GASPNode = map[string]interface{}

// Outpoint defines model for Outpoint.
type Outpoint struct {
	// OutputIndex Output index
	OutputIndex uint32 `json:"outputIndex"`

	// Txid Transaction ID
	Txid string `json:"txid"`
}

// STEAK defines model for STEAK.
type STEAK map[string]AdmittanceInstructions

// SubmitTransaction defines model for SubmitTransaction.
type SubmitTransaction struct {
	STEAK STEAK `json:"STEAK"`
}

// RequestForeignGASPNodeResponse GASP node data structure
type RequestForeignGASPNodeResponse = GASPNode

// RequestSyncResponseResponse defines model for RequestSyncResponseResponse.
type RequestSyncResponseResponse = GASPInitialResponse

// SubmitTransactionResponse defines model for SubmitTransactionResponse.
type SubmitTransactionResponse = SubmitTransaction
