// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdmittanceInstructions defines model for AdmittanceInstructions.
type AdmittanceInstructions struct {
	AncillaryTxIDs []string `json:"AncillaryTxIDs"`
	CoinsRemoved   []uint32 `json:"CoinsRemoved"`
	CoinsToRetain  []uint32 `json:"CoinsToRetain"`
	OutputsToAdmit []uint32 `json:"OutputsToAdmit"`
}

// STEAK defines model for STEAK.
type STEAK map[string]AdmittanceInstructions

// SubmitTransaction defines model for SubmitTransaction.
type SubmitTransaction struct {
	STEAK STEAK `json:"STEAK"`
}

// TopicManagerMetadata defines model for TopicManagerMetadata.
type TopicManagerMetadata struct {
	IconURL          *string `json:"iconURL"`
	InformationURL   *string `json:"informationURL"`
	Name             string  `json:"name"`
	ShortDescription string  `json:"shortDescription"`
	Version          *string `json:"version"`
}

// TopicManagersList defines model for TopicManagersList.
type TopicManagersList map[string]TopicManagerMetadata

// SubmitTransactionResponse defines model for SubmitTransactionResponse.
type SubmitTransactionResponse = SubmitTransaction

// TopicManagersListResponse defines model for TopicManagersListResponse.
type TopicManagersListResponse = TopicManagersList
