// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdmittanceInstructions defines model for AdmittanceInstructions.
type AdmittanceInstructions struct {
	AncillaryTxIDs []string `json:"ancillaryTxIDs"`
	CoinsRemoved   []uint32 `json:"coinsRemoved"`
	CoinsToRetain  []uint32 `json:"coinsToRetain"`
	OutputsToAdmit []uint32 `json:"outputsToAdmit"`
}

// LookupServiceProviderMetadata defines model for LookupServiceProviderMetadata.
type LookupServiceProviderMetadata struct {
	IconURL          *string `json:"iconURL"`
	InformationURL   *string `json:"informationURL"`
	Name             string  `json:"name"`
	ShortDescription string  `json:"shortDescription"`
	Version          *string `json:"version"`
}

// LookupServiceProvidersList defines model for LookupServiceProvidersList.
type LookupServiceProvidersList map[string]LookupServiceProviderMetadata

// STEAK defines model for STEAK.
type STEAK map[string]AdmittanceInstructions

// SubmitTransaction defines model for SubmitTransaction.
type SubmitTransaction struct {
	STEAK STEAK `json:"STEAK"`
}

// LookupServiceProvidersListResponse defines model for LookupServiceProvidersListResponse.
type LookupServiceProvidersListResponse = LookupServiceProvidersList

// TopicManagerDocumentation defines model for TopicManagerDocumentation.
type TopicManagerDocumentation struct {
	// Documentation Markdown-formatted documentation for the topic manager
	Documentation string `json:"documentation"`
}

// SubmitTransactionResponse defines model for SubmitTransactionResponse.
type SubmitTransactionResponse = SubmitTransaction

// TopicManagerDocumentationResponse defines model for TopicManagerDocumentationResponse.
type TopicManagerDocumentationResponse = TopicManagerDocumentation
