// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// SubmitTransactionParams defines parameters for SubmitTransaction.
type SubmitTransactionParams struct {
	XTopics []string `json:"x-topics"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/admin/syncAdvertisements)
	AdvertisementsSync(c *fiber.Ctx) error

	// (POST /api/v1/submit)
	SubmitTransaction(c *fiber.Ctx, params SubmitTransactionParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// AdvertisementsSync operation middleware
func (siw *ServerInterfaceWrapper) AdvertisementsSync(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.AdvertisementsSync(c)
}

// SubmitTransaction operation middleware
func (siw *ServerInterfaceWrapper) SubmitTransaction(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SubmitTransactionParams

	headers := c.GetReqHeaders()

	// ------------- Required header parameter "x-topics" -------------
	if value, found := headers[http.CanonicalHeaderKey("x-topics")]; found {
		var XTopics []string

		err = runtime.BindStyledParameterWithOptions("simple", "x-topics", value[0], &XTopics, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: true, Required: true})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter x-topics: %w", err).Error())
		}

		params.XTopics = XTopics

	} else {
		err = fmt.Errorf("Header parameter x-topics is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	return siw.Handler.SubmitTransaction(c, params)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/api/v1/admin/syncAdvertisements", wrapper.AdvertisementsSync)

	router.Post(options.BaseURL+"/api/v1/submit", wrapper.SubmitTransaction)

}
