// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdmittanceInstructions defines model for AdmittanceInstructions.
type AdmittanceInstructions struct {
	AncillaryTxIDs []string `json:"AncillaryTxIDs"`
	CoinsRemoved   []uint32 `json:"CoinsRemoved"`
	CoinsToRetain  []uint32 `json:"CoinsToRetain"`
	OutputsToAdmit []uint32 `json:"OutputsToAdmit"`
}

// STEAK defines model for STEAK.
type STEAK map[string]AdmittanceInstructions

// SubmitTransactionResponse defines model for SubmitTransactionResponse.
type SubmitTransactionResponse struct {
	STEAK STEAK `json:"STEAK"`
}
