openapi: 3.0.4
info:
  version: 1.0.0
  title: Overlay HTTP API
  description: The overlay server API
servers:
  - url: 'http://localhost:3000'
    description: 'Optional server description, e.g. Main (production) server'
tags:
  - name: admin
    description: Admin API endpoints
  - name: non-admin
    description: Non Admin API endpointsa
paths:
  /api/v1/admin/syncAdvertisements:
    post:
      tags:
        - admin
      operationId: AdvertisementsSync
      security:
        - bearerAuth: []
      responses:
        '200':
          description: |
            Advertisement sync request successfully delegated to overlay engine.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Message:
                    type: string
                required:
                  - Message
        '500':
          $ref: '#/paths/~1api~1v1~1submit/post/responses/500'
  /api/v1/arc-ingest:
    post:
      tags:
        - non-admin
      operationId: ArcIngest
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                txid:
                  type: string
                  description: Transaction ID in hexadecimal format
                merklePath:
                  type: string
                  description: Merkle path in hexadecimal format
                blockHeight:
                  type: integer
                  format: uint32
                  description: Block height where the transaction was mined
              required:
                - txid
                - merklePath
                - blockHeight
      responses:
        '200':
          description: Transaction status successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                      - failure
                    description: Status of the operation
                  message:
                    type: string
                    description: Additional information about the operation
                required:
                  - status
                  - message
        '400':
          $ref: '#/paths/~1api~1v1~1submit/post/responses/400'
        '401':
          description: |
            Authentication is required but was not provided or is invalid.
            This error occurs when the client attempts to access a protected resource
            without providing the required authentication credentials.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1v1~1submit/post/responses/400/content/application~1json/schema'
        '403':
          description: |
            The server understood the request, but refuses to authorize it.
            This error occurs when the client has valid authentication but does not have
            the necessary permissions to access the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1v1~1submit/post/responses/400/content/application~1json/schema'
        '408':
          $ref: '#/paths/~1api~1v1~1submit/post/responses/409'
        '500':
          $ref: '#/paths/~1api~1v1~1submit/post/responses/500'
        '504':
          description: |
            The server, while acting as a gateway or proxy, did not receive a timely response
            from the upstream server or some other auxiliary server it needed to access in order to complete the request.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1v1~1submit/post/responses/400/content/application~1json/schema'
  /api/v1/submit:
    post:
      tags:
        - non-admin
      operationId: SubmitTransaction
      parameters:
        - in: header
          name: x-topics
          schema:
            type: array
            items:
              type: string
          required: true
          explode: true
          style: simple
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: object
              properties:
                Transaction:
                  type: string
                  format: binary
                  description: 'Serialized transaction data (e.g., a binary format such as Protobuf or other)'
              required:
                - Transaction
      responses:
        '200':
          description: |
            Overlay engine successfully processed the submitted transaction octet-stream with the specified topic headers.
          content:
            application/json:
              schema:
                type: object
                properties:
                  STEAK:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        OutputsToAdmit:
                          type: array
                          items:
                            type: integer
                            format: uint32
                        CoinsToRetain:
                          type: array
                          items:
                            type: integer
                            format: uint32
                        CoinsRemoved:
                          type: array
                          items:
                            type: integer
                            format: uint32
                        AncillaryTxIDs:
                          type: array
                          items:
                            type: string
                      required:
                        - OutputsToAdmit
                        - CoinsToRetain
                        - CoinsRemoved
                        - AncillaryTxIDs
                required:
                  - STEAK
        '400':
          description: |
            The server cannot process the request due to malformed syntax or invalid input. 
            This error is typically caused by client-side issues, such as missing required parameters, 
            invalid data formats, or incorrect request structures.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: Human-readable error message
        '409':
          description: |
            The server did not receive a complete request within the time it was prepared to wait. 
            This error can occur if the client's request takes too long to process or there is network latency.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1v1~1submit/post/responses/400/content/application~1json/schema'
        '500':
          description: |
            An unexpected condition was encountered on the server, causing the request to fail.
            This error is typically caused by internal issues such as server misconfigurations, 
            database failures, or unhandled exceptions.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1v1~1submit/post/responses/400/content/application~1json/schema'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
